name: flutter_maplibre_geofence
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  maplibre_gl: ^0.20.0
  location: ^5.0.0
  geolocator: ^9.0.2  # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
